#!/usr/bin/env python3
"""Recompute PORTING_BACKLOG.md's "Snapshot baseline" table from live repo state.

This replaces a manual audit (count snapshot files, count SUPPORTED entries, count
mappings/reviewed-*.yaml and mappings/rejected-*.yaml entries by hand) that drifted
between sessions and once undercounted `hooks/` Ported by one (missed
`hermes_hook_common.py`, source `hooks/safety_common.py`, in a hand count).

Ported = fast-lane (`sync_upstream.SUPPORTED`) entries + reviewed-hook/reviewed-script
lane entries, grouped by top-level source-path prefix. Rejected = rejected-hook/
rejected-script lane entries whose rejection was not later reversed by a
`superseded_by` field (see `bake_animation.py` in mappings/rejected-scripts.yaml for
that exact case — it counts as Ported, not Rejected). Left out = Files in snapshot -
Ported - Rejected.

Usage:
    python3 scripts/update_backlog_counts.py            # recompute and write if changed
    python3 scripts/update_backlog_counts.py --check    # exit 1 if the file is stale, no write

Called automatically by `sync_upstream.py --sync` at the end of every sync, and checked
by `validate_output.py` so a manual mappings/ edit that changes Ported/Rejected without
a sync still gets caught in CI.
"""
from __future__ import annotations

import argparse
import re
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SNAPSHOT = ROOT / "upstream" / "claude-code-config" / "snapshot"
BACKLOG = ROOT / "PORTING_BACKLOG.md"
LOCK = ROOT / "upstream.lock.json"

BEGIN_MARKER = "<!-- BEGIN SNAPSHOT_BASELINE_TABLE (auto-generated by scripts/update_backlog_counts.py — do not hand-edit) -->"
END_MARKER = "<!-- END SNAPSHOT_BASELINE_TABLE -->"

# (display label, snapshot-relative prefix; None = top-level files with no "/")
AREAS: list[tuple[str, str | None]] = [
    ("Root docs/config", None),
    (".claude-plugin/", ".claude-plugin/"),
    (".github/", ".github/"),
    ("agents/", "agents/"),
    ("alternatives/", "alternatives/"),
    ("docs/", "docs/"),
    ("evals/", "evals/"),
    ("hooks/", "hooks/"),
    ("principles/", "principles/"),
    ("references/", "references/"),
    ("rules/", "rules/"),
    ("scripts/", "scripts/"),
    ("skills/", "skills/"),
    ("templates/", "templates/"),
    ("workflows/", "workflows/"),
]


def prefix_of(path: str) -> str:
    return path.split("/", 1)[0] + "/" if "/" in path else "root"


def count_snapshot_files() -> dict[str, int]:
    counts: dict[str, int] = {"root": sum(1 for p in SNAPSHOT.iterdir() if p.is_file())}
    for _, prefix in AREAS[1:]:
        d = SNAPSHOT / prefix.rstrip("/")
        counts[prefix] = sum(1 for f in d.rglob("*") if f.is_file()) if d.is_dir() else 0
    return counts


def load_supported_by_prefix() -> Counter:
    sys.path.insert(0, str(ROOT / "scripts"))
    import sync_upstream as su  # noqa: E402  (path inserted above)

    return Counter(prefix_of(k) for k in su.SUPPORTED)


def parse_manifest_entries(path: Path) -> list[dict[str, object]]:
    """Minimal field extractor (source_path, presence of superseded_by) for the four
    mappings/{reviewed,rejected}-{hooks,scripts}.yaml manifests — deliberately not a
    full YAML parser, matching validate_output.py's parse_reviewed_hooks()/
    parse_reviewed_scripts() convention (no PyYAML dependency in CI)."""
    if not path.is_file():
        return []
    entries: list[dict[str, object]] = []
    current: dict[str, object] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        if re.match(r"^- \S+:", line):
            if current:
                entries.append(current)
            current = {}
        m = re.match(r"^\s*source_path:\s*(\S+)\s*$", line)
        if m:
            current["source_path"] = m.group(1)
        if re.match(r"^\s*superseded_by:\s*\S", line):
            current["superseded_by"] = True
    if current:
        entries.append(current)
    return entries


def compute_rows() -> list[tuple[str, int, int, int, int]]:
    files_by_prefix = count_snapshot_files()
    fast_lane_by_prefix = load_supported_by_prefix()

    reviewed = parse_manifest_entries(ROOT / "mappings" / "reviewed-hooks.yaml") + parse_manifest_entries(
        ROOT / "mappings" / "reviewed-scripts.yaml"
    )
    rejected = parse_manifest_entries(ROOT / "mappings" / "rejected-hooks.yaml") + parse_manifest_entries(
        ROOT / "mappings" / "rejected-scripts.yaml"
    )

    reviewed_by_prefix = Counter(prefix_of(str(e["source_path"])) for e in reviewed if "source_path" in e)
    rejected_by_prefix = Counter(
        prefix_of(str(e["source_path"])) for e in rejected if "source_path" in e and not e.get("superseded_by")
    )

    rows = []
    for label, prefix in AREAS:
        key = prefix or "root"
        files = files_by_prefix.get(key, 0)
        ported = fast_lane_by_prefix.get(key, 0) + reviewed_by_prefix.get(key, 0)
        rej = rejected_by_prefix.get(key, 0)
        rows.append((label, files, ported, rej, files - ported - rej))
    return rows


def lane_detail_lines(rows: list[tuple[str, int, int, int, int]]) -> list[str]:
    """One bullet per area that has any reviewed-lane or rejected activity, naming the
    exact files involved — mechanical, so it can never drift the way hand-written
    footnote prose did."""
    reviewed = parse_manifest_entries(ROOT / "mappings" / "reviewed-hooks.yaml") + parse_manifest_entries(
        ROOT / "mappings" / "reviewed-scripts.yaml"
    )
    rejected = parse_manifest_entries(ROOT / "mappings" / "rejected-hooks.yaml") + parse_manifest_entries(
        ROOT / "mappings" / "rejected-scripts.yaml"
    )
    lines = []
    for label, prefix in AREAS:
        key = prefix or "root"
        reviewed_here = sorted(
            str(e["source_path"]).rsplit("/", 1)[-1] for e in reviewed if "source_path" in e and prefix_of(str(e["source_path"])) == key
        )
        rejected_here = sorted(
            str(e["source_path"]).rsplit("/", 1)[-1]
            for e in rejected
            if "source_path" in e and prefix_of(str(e["source_path"])) == key and not e.get("superseded_by")
        )
        superseded_here = sorted(
            str(e["source_path"]).rsplit("/", 1)[-1]
            for e in rejected
            if "source_path" in e and prefix_of(str(e["source_path"])) == key and e.get("superseded_by")
        )
        if not reviewed_here and not rejected_here and not superseded_here:
            continue
        bits = []
        if reviewed_here:
            bits.append(f"reviewed-lane Ported ({len(reviewed_here)}): " + ", ".join(f"`{n}`" for n in reviewed_here))
        if rejected_here:
            bits.append(f"Rejected ({len(rejected_here)}): " + ", ".join(f"`{n}`" for n in rejected_here))
        if superseded_here:
            bits.append(
                "initially rejected, later superseded/accepted (counts as Ported, not Rejected): "
                + ", ".join(f"`{n}`" for n in superseded_here)
            )
        lines.append(f"- `{prefix or 'root'}`: " + "; ".join(bits))
    return lines


def render_block(rows: list[tuple[str, int, int, int, int]]) -> str:
    lock_sha = "unknown"
    if LOCK.is_file():
        import json

        lock_sha = json.loads(LOCK.read_text(encoding="utf-8"))["upstream"].get("last_synced_sha", "unknown")

    lines = [BEGIN_MARKER, ""]
    lines.append("| Area | Files in snapshot | Ported | Rejected | Left out |")
    lines.append("| --- | ---: | ---: | ---: | ---: |")
    for label, files, ported, rej, left in rows:
        area_cell = label if label == "Root docs/config" else f"`{label}`"
        lines.append(f"| {area_cell} | {files} | {ported} | {rej} | {left} |")
    total_files = sum(r[1] for r in rows)
    total_ported = sum(r[2] for r in rows)
    total_rejected = sum(r[3] for r in rows)
    total_left = sum(r[4] for r in rows)
    lines.append(f"| **Total** | **{total_files}** | **{total_ported}** | **{total_rejected}** | **{total_left}** |")
    lines.append("")
    lines.append(
        "Lane detail (only areas with reviewed-lane or rejected activity; fast-lane-only areas "
        "are omitted here, see `Ported` column above):"
    )
    lines.append("")
    lines.extend(lane_detail_lines(rows))
    lines.append("")
    lines.append(f"_Last recomputed against upstream commit `{lock_sha}` (`upstream.lock.json`'s `last_synced_sha`)._")
    lines.append("")
    lines.append(END_MARKER)
    return "\n".join(lines)


def apply(check_only: bool) -> bool:
    """Returns True if the file already matched (or was updated to match); False if
    --check found drift (caller should treat that as a failure)."""
    text = BACKLOG.read_text(encoding="utf-8")
    if BEGIN_MARKER not in text or END_MARKER not in text:
        print(f"ERROR: markers not found in {BACKLOG}", file=sys.stderr)
        return False
    before, rest = text.split(BEGIN_MARKER, 1)
    _, after = rest.split(END_MARKER, 1)
    new_block = render_block(compute_rows())
    new_text = before + new_block + after
    if new_text == text:
        print("PORTING_BACKLOG.md Snapshot baseline table is up to date.")
        return True
    if check_only:
        print("STALE: PORTING_BACKLOG.md Snapshot baseline table does not match live repo state.", file=sys.stderr)
        print("Run: python3 scripts/update_backlog_counts.py", file=sys.stderr)
        return False
    BACKLOG.write_text(new_text, encoding="utf-8")
    print("Updated PORTING_BACKLOG.md Snapshot baseline table.")
    return True


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    ok = apply(check_only=args.check)
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
